---
- hosts: localhost
  remote_user: alok
  become: no
  gather_facts: no
  tasks:
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name: docker

    - name: Build an image and push
      docker_image:
        build:
          path: .
        name: docker-ansible
        tag: v1
        source: build
        state: present

    - name: Running the container
      docker_container:
        name: test-os
        image: docker-ansible:v1 
        state: started
        auto_remove: true
        ports: 
        - "3000:3000"
      register: docker_info
